# Generated by Django 5.0.7 on 2024-07-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webbform',
            name='emailRecieptsEnaabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webbform',
            name='success_message',
            field=models.TextField(default=''),
        ),
    ]
