# Generated by Django 5.0.7 on 2024-07-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_webbform_emailrecieptsenaabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webbform',
            old_name='emailRecieptsEnaabled',
            new_name='emailRecieptsEnabled',
        ),
    ]
